CREATE TABLE FORMS(
ID INT IDENTITY(1,1) PRIMARY KEY,
GUID VARCHAR(MAX) NOT NULL,
BSCID INT NOT NULL,
FIRST_NAME VARCHAR(MAX) NOT NULL,
LAST_NAME VARCHAR(MAX) NOT NULL,
MANAGER_EMAIL VARCHAR(MAX) NOT NULL,
REQUEST VARCHAR(MAX) NOT NULL,
TIME_STAMP DATETIME NOT NULL,
APPROVED_BY VARCHAR(MAX) NULL,
DENIED_BY VARCHAR(MAX) NULL,
COMMENTS VARCHAR(MAX) NULL
);

CREATE PROCEDURE dbo.STORE_FORM_DATA
  @GUID VARCHAR(MAX) = NULL,
  @BSCID INT,
  @FIRST_NAME VARCHAR(MAX) = NULL,
  @LAST_NAME VARCHAR(MAX) = NULL,
  @MANAGER_EMAIL VARCHAR(MAX) = NULL,
  @REQUEST VARCHAR(MAX) = NULL,
  @TIME_STAMP DATETIME
  AS
  INSERT INTO FORMS VALUES(
    @GUID,
    @BSCID,
    @FIRST_NAME,
    @LAST_NAME,
    @MANAGER_EMAIL,
    @REQUEST,
    @TIME_STAMP
  )
GO

CREATE PROCEDURE dbo.SEND_FORM_DATA
  @GUID VARCHAR(MAX) = NULL
  AS
  SELECT * FROM FORMS WHERE GUID = @GUID
  FOR JSON PATH
GO

CREATE PROCEDURE dbo.SEND_ALL_FORM_DATA
  AS
  SELECT * FROM FORMS
  FOR JSON PATH, ROOT('FORMS')
GO

CREATE PROCEDURE dbo.DELETE_FORM_DATA
  @GUID VARCHAR
  AS
  DELETE FROM FORMS WHERE GUID = @GUID
GO


CREATE PROCEDURE dbo.UPDATE_FORM_DATA
  @APPROVER VARCHAR,
  @APPROVAL VARCHAR,
  @GUID VARCHAR
  AS
  IF (@APPROVAL = 'YES')
    UPDATE FORMS SET APPROVED_BY = @APPROVER WHERE GUID = @GUID
  ELSE
    UPDATE FORMS SET DENIED_BY = @APPROVER WHERE GUID = @GUID
GO
